// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mvhwG2W3d8_mIus9aUMtJQv-79J2LqM',
    appId: '1:521152251141:web:7f1e973e6e986c6304e36c',
    messagingSenderId: '521152251141',
    projectId: 'se346-442ff',
    authDomain: 'se346-442ff.firebaseapp.com',
    storageBucket: 'se346-442ff.appspot.com',
    measurementId: 'G-F61BT1R429',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5akBq3OkoMagsD0173yJE2krH5CPctfg',
    appId: '1:521152251141:android:90fb3f4c2b98a57104e36c',
    messagingSenderId: '521152251141',
    projectId: 'se346-442ff',
    storageBucket: 'se346-442ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTPs_5HbDJUMQKi8HKDBugvZqxasEpT3o',
    appId: '1:521152251141:ios:31774654e87698bc04e36c',
    messagingSenderId: '521152251141',
    projectId: 'se346-442ff',
    storageBucket: 'se346-442ff.appspot.com',
    iosBundleId: 'com.example.se346Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTPs_5HbDJUMQKi8HKDBugvZqxasEpT3o',
    appId: '1:521152251141:ios:31774654e87698bc04e36c',
    messagingSenderId: '521152251141',
    projectId: 'se346-442ff',
    storageBucket: 'se346-442ff.appspot.com',
    iosBundleId: 'com.example.se346Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7mvhwG2W3d8_mIus9aUMtJQv-79J2LqM',
    appId: '1:521152251141:web:c7fe0157bd85e99e04e36c',
    messagingSenderId: '521152251141',
    projectId: 'se346-442ff',
    authDomain: 'se346-442ff.firebaseapp.com',
    storageBucket: 'se346-442ff.appspot.com',
    measurementId: 'G-56MW30Q66F',
  );

}